trigger:
  branches:
    include:
      - main
  paths:
    include:
      - databricks
pool:
  vmImage: ubuntu-latest

resources:
 repositories:
   - repository: VarTemplates
     displayName: Project Specific Variable Templates
     type: git
     name: Global_Satellite/Global_Satellite
     ref: main

stages:
  - template: devops/ADB/CI/build_databricks.yml@VarTemplates
    parameters:
      varPath: /devops/config/common/variables.yml@VarTemplates
      envVarPath: /devops/config/dev/variables.yml@VarTemplates
      agent_pool: ubuntu-latest
      buildOnlyNewNotebooks: false
      
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
#DEV DEPLOY
    - template: devops/ADB/CD/deploy_databricks.yml@Vartemplates
      parameters:
        varPath: /devops/config/common/variables.yml@VarTemplates
        envVarPath: /devops/config/dev/variables.yml@VarTemplates
        environment: Global_satellite_dev
        agent_pool: windows-latest
